//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binalar
    {
        public int BinaId { get; set; }
        public string binaAdi { get; set; }
        public int daireSayisi { get; set; }
    }
}
