//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbB703CB358AEntities1 : DbContext
    {
        public dbB703CB358AEntities1()
            : base("name=dbB703CB358AEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dairelerSet> dairelerSet { get; set; }
        public DbSet<kisilerSet> kisilerSet { get; set; }
        public DbSet<OdemelerSet> OdemelerSet { get; set; }
        public DbSet<OgSet> OgSet { get; set; }
    }
}
