//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class dairelerSet
    {
        public int daireId { get; set; }
        public int daireno { get; set; }
        public int kisi_id { get; set; }
        public int ev_sahibi_id { get; set; }
        public int binaId { get; set; }
    }
}
