//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisilerSet
    {
        public int kisiId { get; set; }
        public string isim { get; set; }
        public string telefon { get; set; }
        public int bina_id { get; set; }
        public int daire_id { get; set; }
    }
}
