//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgSet
    {
        public OgSet()
        {
            this.OdemelerSet = new HashSet<OdemelerSet>();
        }
    
        public int OgId { get; set; }
        public double Tutar { get; set; }
        public string Tur { get; set; }
        public string isim { get; set; }
        public bool taksitli { get; set; }
        public Nullable<double> taksitlitutar { get; set; }
        public Nullable<int> taksitsayisi { get; set; }
    
        public virtual ICollection<OdemelerSet> OdemelerSet { get; set; }
    }
}
